FROM node:20-alpine AS builder
WORKDIR /kubernetes-next-app

COPY ./kubernetes-next-app .

RUN npm install
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /kubernetes-next-app

RUN mkdir .next

COPY --from=builder /kubernetes-next-app/public ./public
COPY --from=builder /kubernetes-next-app/.next/standalone ./
COPY --from=builder /kubernetes-next-app/.next/static ./.next/static

EXPOSE 3000

ENV PORT=3000

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/config/next-config-js/output
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]