apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-next-app
spec:
  containers:
  - name: kubernetes-next-app
    image: kubernetes-next-app:1.0.0
    ports:
      - containerPort: 3000
        name: http
        protocol: TCP
    readinessProbe:
      httpGet:
          path: /api
          port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
---
kind: Service
apiVersion: v1
metadata:
  name: kubernetes-next-app-service
spec:
  selector:
    app: kubernetes-next-app
  ports:
  # Default port used by the image
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-next-app-node-port
spec:
  type: NodePort
  selector:
    app: hostname
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000