apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-next-app
spec:
  containers:
  - name: kubernetes-next-app
    image: kubernetes-next-app:1.0.0
    ports:
      - containerPort: 3000
        name: http
        protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: kubernetes-next-app-service
spec:
  selector:
    app: kubernetes-next-app
  ports:
  # Default port used by the image
  - port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /kubernetes-next-app
        backend:
          service:
            name: kubernetes-next-app
            port:
              number: 3000