apiVersion: apps/v1
# # Here we define a single pod running the Kubernetes next app
# kind: Pod
# metadata:
#   name: kubernetes-next-app
#   labels:
#     app: kubernetes-next-app
# spec:
#   containers:
#   - name: kubernetes-next-app
#     image: kubernetes-next-app:1.0.0
#     # We expose the 3000 pod where the container runs the application
#     ports:
#       - containerPort: 3000
#         name: http
#         protocol: TCP
#     # We also set a readinessProbe, which lets kubelet (running on the
#     # node) know when the pod is ready to serve traffic. We need this so
#     # the service knows the pod is ready
#     readinessProbe:
#       httpGet:
#         path: /api
#         port: 3000
#       initialDelaySeconds: 30
#       timeoutSeconds: 1
#       periodSeconds: 10
#       failureThreshold: 3
kind: Deployment
metadata:
  name: kubernetes-next-app-deployment
  labels:
    app: kubernetes-next-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-next-app
  template:
    metadata:
      labels:
        app: kubernetes-next-app
    spec:
      volumes:
        - name: kna-pv-storage
          persistentVolumeClaim:
            claimName: kna-pv-claim
      containers:
      - name: kubernetes-next-app
        image: kubernetes-next-app:1.0.0
        volumeMounts:
        - mountPath: /mnt/data
          name: kna-pv-storage
        # We expose the 3000 pod where the container runs the application
        ports:
          - containerPort: 3000
            name: http
            protocol: TCP
        # We also set a readinessProbe, which lets kubelet (running on the
        # node) know when the pod is ready to serve traffic. We need this so
        # the service knows the pod is ready
        readinessProbe:
          httpGet:
            path: /api
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
---
# Here we define a service. This can group a number of pods together
# under a single name and IP address/ DNS name
kind: Service
apiVersion: v1
metadata:
  name: kubernetes-next-app-service
spec:
  selector:
    app: kubernetes-next-app
  ports:
  - port: 3000
    targetPort: 3000